# -*- coding: utf-8 -*-
"""Untitled122.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gMF9DXYAWLkQ4rX_QbohYhg8rJ9ttxSl
"""

import streamlit as st
import pandas as pd
import numpy as np
import pickle

# Load the model and preprocessor
with open('logistic_regression_model.pkl', 'rb') as file:
    model = pickle.load(file)

with open('preprocessor.pkl', 'rb') as file:
    preprocessor = pickle.load(file)

st.title('Titanic Survival Prediction')

st.sidebar.header('User Input Features')

def user_input_features():
    age = st.sidebar.slider('Age', 0, 80, 29)
    fare = st.sidebar.slider('Fare', 0, 500, 32)
    sex = st.sidebar.selectbox('Sex', ('male', 'female'))
    embarked = st.sidebar.selectbox('Embarked', ('C', 'Q', 'S'))

    data = {'Age': age,
            'Fare': fare,
            'Sex': sex,
            'Embarked': embarked}
    features = pd.DataFrame(data, index=[0])
    return features

input_df = user_input_features()

# Display user input features
st.subheader('User Input features')
st.write(input_df)

# Preprocess the input features
input_preprocessed = preprocessor.transform(input_df)

# Make predictions
prediction = model.predict(input_preprocessed)
prediction_proba = model.predict_proba(input_preprocessed)

st.subheader('Prediction')
survival = np.array(['Not Survived', 'Survived'])
st.write(survival[prediction][0])

st.subheader('Prediction Probability')
st.write(prediction_proba)